name: Bot de Recordatorios Diario

on:
  schedule:
    # esto corre todos los días a las 22:00 hora UTC, hacer conversion a GTM-3 | GTM-4 (Santiago)
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar librerías
      run: |
        pip install python-telegram-bot icalevents pytz

    - name: Debug secrets
      env:
        TOKEN: ${{ secrets.TOKEN_BOT }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        ICAL_URL: ${{ secrets.ICAL }}
      run: |
        echo "TOKEN=${TOKEN:+OK}"
        echo "CHAT_ID=${CHAT_ID:+OK}"
        echo "ICAL_URL=${ICAL_URL:+OK}"

    - name: Ejecutar el bot
      env:
        TOKEN: ${{ secrets.TOKEN_BOT }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        ICAL_URL: ${{ secrets.ICAL }}
      run: python main.py
